apiVersion: v2
name: kubelb-manager
description: Helm chart for KubeLB Manager
icon: https://raw.githubusercontent.com/kubermatic/kubelb/main/docs/kubelb-logo.png
type: application
maintainers:
  - name: Kubermatic
    email: support@kubermatic.com
    url: https://kubermatic.com

# Helm chart Version.
version: v1.2.0
# Application version to be deployed.
appVersion: v1.2.0

dependencies:
  - name: kubelb-addons
    repository: oci://quay.io/kubermatic/helm-charts
    condition: kubelb-addons.enabled
    version: v0.1.0
