apiVersion: v2
name: kubelb-addons
description: Helm chart for KubeLB Addons
icon: https://raw.githubusercontent.com/kubermatic/kubelb/main/docs/kubelb-logo.png
type: application
maintainers:
  - name: Kubermatic
    email: support@kubermatic.com
    url: https://kubermatic.com
version: v0.2.0
appVersion: v0.2.0
dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
    version: 4.14.1
  - name: gateway-helm
    repository: oci://docker.io/envoyproxy
    condition: envoy-gateway.enabled
    version: 1.6.1
    alias: envoy-gateway
  - name: cert-manager
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
    version: 1.19.2
  - name: external-dns
    repository: https://kubernetes-sigs.github.io/external-dns
    condition: external-dns.enabled
    version: 1.20.0
  - name: metallb
    repository: https://metallb.github.io/metallb
    condition: metallb.enabled
    version: 0.15.3
  - name: kgateway-crds
    repository: oci://cr.kgateway.dev/kgateway-dev/charts
    condition: kgateway.crds.enabled
    version: v2.1.2
  - name: kgateway
    repository: oci://cr.kgateway.dev/kgateway-dev/charts
    condition: kgateway.enabled
    version: v2.1.2
